[package]
name = "stanley"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.1"
clap = { version = "3.1.6", features = ["derive"] }
spin_sleep = "1.1.1"
fake_clock = "0.3.1"
